server:
  port: 9010

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/dietbuilder-engine-gateway
      auto-index-creation: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      exchange: dietbuilder.engine.gateway
      routing-key: user-details